- name: Restart nova services
  service:
    name: "{{ item }}"
    state: restarted
    pattern: "{{ item }}"
  with_items: nova_service_names
  failed_when: false

- name: Restart libvirtd
  service:
    name: "libvirtd"
    state: "restarted"
    pattern: "libvirtd"
