keystone_mariadb_address: "127.0.0.1"
keystone_mariadb_database: "keystone"
keystone_mariadb_user: "keystone"
keystone_mariadb_password: "keystone"

keystone_httpd_address: "127.0.0.1"
keystone_auth_admin_token: "admin_token"
keystone_memcached_address: "127.0.0.1"


## Role info
keystone_role_name: admin
keystone_default_role_name: _member_

keystone_auth_admin_password: "admin"
keystone_service_password: keystone

keystone_admin_port: 35357
keystone_admin_user_name: admin
keystone_admin_tenant_name: admin
keystone_admin_description: Admin Tenant

## Service Type and Data
keystone_service_region: "RegionOne"
keystone_service_name: "keystone"
keystone_service_port: 5000
keystone_service_proto: "http"
keystone_service_publicuri_proto: "{{ openstack_service_publicuri_proto | default(keystone_service_proto) }}"
keystone_service_adminuri_proto: "{{ openstack_service_adminuri_proto | default(keystone_service_proto) }}"
keystone_service_internaluri_proto: "{{ openstack_service_internaluri_proto | default(keystone_service_proto) }}"
keystone_service_type: "identity"
keystone_service_description: "keystone identity service" 
keystone_service_user_name: "keystone"
keystone_service_tenant_name: "service"


keystone_service_publicuri: "{{ keystone_service_publicuri_proto }}://{{ external_lb_vip_address }}:{{ keystone_service_port }}"
keystone_service_internaluri: "{{ keystone_service_internaluri_proto }}://{{ internal_lb_vip_address }}:{{ keystone_service_port }}"
keystone_service_adminuri: "{{ keystone_service_adminuri_proto }}://{{ internal_lb_vip_address }}:{{ keystone_admin_port }}"

keystone_service_publicurl_v2: "{{ keystone_service_publicuri }}/v2.0"
keystone_service_internalurl_v2: "{{ keystone_service_internaluri }}/v2.0"
keystone_service_adminurl_v2: "{{ keystone_service_adminuri }}/v2.0"

keystone_service_publicurl_v3: "{{ keystone_service_publicuri }}/v3"
keystone_service_internalurl_v3: "{{ keystone_service_internaluri }}/v3"
keystone_service_adminurl_v3: "{{ keystone_service_adminuri }}/v3"

keystone_service_publicurl: "{{ keystone_service_publicurl_v3 }}"
keystone_service_internalurl: "{{ keystone_service_internalurl_v3 }}"
keystone_service_adminurl: "{{ keystone_service_adminurl_v3 }}"

keystone_service_adminuri_insecure: false
