- include: nova_install.yml
- include: nova_console_install.yml
- include: nova_db_setup.yml
- include: nova_service.yml
- include: nova_service_setup.yml

- include: nova_compute.yml
  when: >
    inventory_hostname in groups['nova_compute']
