- include: nova_console_spice_install.yml
  when:
    - inventory_hostname in groups['nova_console']
    - nova_console_type == "spice"

- include: nova_console_novnc_install.yml
  when:
    - inventory_hostname in groups['nova_console']
    - nova_console_type == "novnc"
