- name: Install yum packages
  yum:
    name: "{{ item }}"
    state: latest
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: nova_compute_kvm_yum_packages
