- name: Get package from git
  git:
    repo: "{{ nova_spicehtml5_git_repo }}"
    dest: "/usr/share/spice-html5"
    clone: "yes"
    update: "yes"
    version: "{{ nova_spicehtml5_git_install_branch }}"
    force: yes
  register: git_clone
  until: git_clone|success
  retries: 5
  delay: 2
