# Create an service tenant
- name: Ensure service tenant
  keystone:
    command: "ensure_tenant"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    tenant_name: "{{ keystone_service_tenant_name }}"
    description: "{{ keystone_service_description }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

# Create an admin tenant
- name: Ensure admin tenant
  keystone:
    command: "ensure_tenant"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    tenant_name: "{{ keystone_admin_tenant_name }}"
    description: "{{ keystone_admin_description }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

# Create an admin user
- name: Ensure Admin user
  keystone:
    command: "ensure_user"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    user_name: "{{ keystone_admin_user_name }}"
    tenant_name: "{{ keystone_admin_tenant_name }}"
    password: "{{ keystone_auth_admin_password }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10
  tags:
    - keystone-api-setup
    - keystone-setup

# Create an admin role
- name: Ensure Admin role
  keystone:
    command: "ensure_role"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    role_name: "{{ keystone_role_name }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

# Add a role to the user
- name: Ensure Admin user to Admin role
  keystone:
    command: "ensure_user_role"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    user_name: "{{ keystone_admin_user_name }}"
    tenant_name: "{{ keystone_admin_tenant_name }}"
    role_name: "{{ keystone_role_name }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

# Add the default user role
- name: Ensure default keystone user role
  keystone:
    command: "ensure_role"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    role_name: "{{ keystone_default_role_name }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_member_role
  until: add_member_role|success
  retries: 5
  delay: 10

# Create a service
- name: Ensure Keystone Service
  keystone:
    command: "ensure_service"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    service_name: "{{ keystone_service_name }}"
    service_type: "{{ keystone_service_type }}"
    description: "{{ keystone_service_description }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

# Create a service user
- name: Ensure Keystone user
  keystone:
    command: "ensure_user"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    user_name: "{{ keystone_service_user_name }}"
    tenant_name: "{{ keystone_service_tenant_name }}"
    password: "{{ keystone_service_password }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

# Add a role to the user
- name: Ensure Keystone user to Admin role
  keystone:
    command: "ensure_user_role"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    user_name: "{{ keystone_service_user_name }}"
    tenant_name: "{{ keystone_service_tenant_name }}"
    role_name: "{{ keystone_role_name }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

# Create an endpoint
- name: Ensure Keystone Endpoint
  keystone:
    command: "ensure_endpoint"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    region_name: "{{ keystone_service_region }}"
    service_name: "{{ keystone_service_name }}"
    service_type: "{{ keystone_service_type }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
    endpoint_list:
      - url: "{{ keystone_service_publicurl }}"
        interface: "public"
      - url: "{{ keystone_service_adminurl }}"
        interface: "admin"
      - url: "{{ keystone_service_internalurl }}"
        interface: "internal"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10

