- name: Ensure Rabbitmq vhost
  rabbitmq_vhost:
    name: "{{ neutron_rabbitmq_vhost }}"
    state: "present"
  delegate_to: "{{ groups['rabbitmq_all'][0] }}"
  tags:
    - neutron-rabbitmq
    - neutron-rabbitmq-vhost

- name: Ensure rabbitmq user
  rabbitmq_user:
    user: "{{ neutron_rabbitmq_userid }}"
    password: "{{ neutron_rabbitmq_password }}"
    vhost: "{{ neutron_rabbitmq_vhost }}"
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    state: "present"
  delegate_to: "{{ groups['rabbitmq_all'][0] }}"
  tags:
    - neutron-rabbitmq
    - neutron-rabbitmq-user
